name 'chef_adventure_works'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef_adventure_works'
long_description 'Installs/Configures chef_adventure_works'
version '0.1.0'

depends 'windows', '~> 1.44.0'
depends 'iis', '~> 4.2.0'
depends 'chef-client', '~> 5.0.0'
